# Generated by Django 5.1.1 on 2024-09-20 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(default=datetime.date(2002, 3, 21)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="racecategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
