# Generated by Django 5.1.1 on 2024-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karting", "0002_remove_customuser_age_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="max_participants",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
