# Generated by Django 5.1.1 on 2024-09-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karting", "0003_race_max_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="kart",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
