# Generated by Django 5.1.1 on 2024-09-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("karting", "0005_race_karts_returned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="karts_returned",
        ),
    ]
